version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: 1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - |
        if echo "$CODEBUILD_WEBHOOK_HEAD_REF" | grep "refs/heads/"; then
          export GIT_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/} | sed "s/\//\_/")
        else
          export GIT_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/}| sed "s/\//\_/")
        fi
      - |
        if [ "$GIT_BRANCH" = "" ] ; then
          GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
          export GIT_BRANCH=$(echo "$GIT_BRANCH" | sed "s/\//\_/")
        fi
      - |
        if [ "$GIT_BRANCH" = "" ] ; then
          GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          GIT_BRANCH=${GIT_BRANCH#remotes/origin/};
          export GIT_BRANCH=$(echo "$GIT_BRANCH" | sed "s/\//\_/")
        fi
      - echo "Branch name $GIT_BRANCH"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the ECR image $REPOSITORY_URI:$GIT_BRANCH
      - |
        docker build \
        --tag $REPOSITORY_URI:$GIT_BRANCH \
        --tag $REPOSITORY_URI:latest \
        -f Dockerfile .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the ECR images $REPOSITORY_URI:$GIT_BRANCH
      - docker push $REPOSITORY_URI:$GIT_BRANCH
      - docker push $REPOSITORY_URI:latest
